version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-nestjs-api-gen
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nestjs-api-generator
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-nestjs-api-gen
    ports:
      - "6379:6379"

volumes:
  pgdata:
